# fly.toml app configuration file generated for questlog-web on 2026-05-16T17:37:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'questlog-web'
primary_region = 'iad'

[build]
  dockerfile = 'frontend/Dockerfile'
  [build.args]
    VITE_API_URL = 'https://questlog-api-snowy-seastar-7669.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
